# Getting started with numpy and jupyterlab

In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/home/ferasnawafleh/.cache/pypoetry/virtualenvs/chess-board-XkUPk6Wf-py3.8/lib/python3.8/site-packages/numpy/__init__.py'>

In [7]:
nums = [1, 2, 3, 4, 5]

In [8]:
nums

[1, 2, 3, 4, 5]

In [9]:
nums_as_np = np.array(nums)

In [10]:
nums_as_np

array([1, 2, 3, 4, 5])

In [11]:
type(nums_as_np)

numpy.ndarray

In [12]:
nums_as_np

array([1, 2, 3, 4, 5])

In [16]:
two_dm_arr = np.array([nums_as_np, [6, 7, 8, 9, 10]])

In [17]:
two_dm_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
two_dm_arr.shape

(2, 5)

In [30]:
two_dm_arr[0:2,2]

array([3, 8])

## Dealing with files

In [37]:
with open('student_scores.csv') as SS:
    print(SS.read())

Hours,Scores
2.5,21
5.1,47
3.2,27
8.5,75
3.5,30
1.5,20
9.2,88
5.5,60
8.3,81
2.7,25
7.7,85
5.9,62
4.5,41
3.3,42
1.1,17
8.9,95
2.5,30
1.9,24
6.1,67
7.4,69
2.7,30
4.8,54
3.8,35
6.9,76
7.8,86


In [43]:
dataset = np.genfromtxt('student_scores.csv', delimiter=',',skip_header=True)

In [44]:
dataset.shape

(25, 2)

In [45]:
dataset

array([[ 2.5, 21. ],
       [ 5.1, 47. ],
       [ 3.2, 27. ],
       [ 8.5, 75. ],
       [ 3.5, 30. ],
       [ 1.5, 20. ],
       [ 9.2, 88. ],
       [ 5.5, 60. ],
       [ 8.3, 81. ],
       [ 2.7, 25. ],
       [ 7.7, 85. ],
       [ 5.9, 62. ],
       [ 4.5, 41. ],
       [ 3.3, 42. ],
       [ 1.1, 17. ],
       [ 8.9, 95. ],
       [ 2.5, 30. ],
       [ 1.9, 24. ],
       [ 6.1, 67. ],
       [ 7.4, 69. ],
       [ 2.7, 30. ],
       [ 4.8, 54. ],
       [ 3.8, 35. ],
       [ 6.9, 76. ],
       [ 7.8, 86. ]])

In [52]:
hours = dataset[:,0]
hours

array([2.5, 5.1, 3.2, 8.5, 3.5, 1.5, 9.2, 5.5, 8.3, 2.7, 7.7, 5.9, 4.5,
       3.3, 1.1, 8.9, 2.5, 1.9, 6.1, 7.4, 2.7, 4.8, 3.8, 6.9, 7.8])

In [55]:
avg_hours = np.sum(hours)/25
avg_hours

5.012

In [56]:
np.mean(hours)

5.012

In [57]:
np.median(hours)

4.8

In [68]:
np.ones([1, 8, 8])

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])